name: Deploy to GitHub Pages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.25.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .env config file
        run: |
          echo "BLOG_ENABLED=${{ vars.BLOG_ENABLED }}" >> .env
          echo "DEPLOYMENT_URL=${{ vars.DEPLOYMENT_URL }}" >> .env
          echo "DEPLOYMENT_BRANCH=${{ vars.DEPLOYMENT_BRANCH }}" >> .env
          echo "BASE_URL=${{ vars.BASE_URL }}" >> .env
          echo "GITHUB_ORG=${{ vars.PORTFOLIO_GITHUB_ORG }}" >> .env
          echo "GITHUB_PROJECT=${{ vars.PORTFOLIO_GITHUB_PROJECT }}" >> .env

      - name: TypeScript type check
        run: pnpm typecheck

      - name: Build website
        run: pnpm build

      - name: Prepare GitHub Pages artifact
        run: cp -r build github-pages

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: github-pages

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    # if: ${{ github.ref_name == github.event.repository.default_branch }}

    if: ${{ github.ref_name == 'development' }} # Temporär für die Einreichung

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4